### ISSUE TITLE
Are you a hacker?

### ISSUE THREAD

**Issue by WalterNadalin** [1mickele/Advent-of-Code-2023#1]
Just wondering, are you a hacker?

**Comment by 1mickele** [comment]
Che casso vuoi

**Comment by WalterNadalin** [comment]
By the way, put a couple of comments in your code if you want someone to read it and understand it

**Comment by 1mickele** [comment]
Ah fuck it, I want just to prove to my potential employer that my GitHub is
not empty and I know my way around code. Btw, why were you looking into my
stuff?

**Comment by WalterNadalin** [comment]
Also, it would not be a bad idea to create a `README.md` with each day's goal ;)

**Comment by WalterNadalin** [comment]
A little bird told me what you were doing

**Comment by WalterNadalin** [comment]
And, you know that this issue is visible to everyone, right? :D

**Comment by 1mickele** [comment]
It's actually forbidden to copy/paste the original text. Anyway, it's not
customary to add comments to rust code, as it self explanatory heuehu.
Indeed, none of the solutions provided them

**Comment by 1mickele** [comment]
They'll have laugh then
